# no "version" line needed with Compose v2
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:8080"
    # DEV: live-reload and faster iteration (remove for prod)
    volumes:
      - ./backend:/app
    command: >
      uvicorn app:app
      --host 0.0.0.0 --port 8080
      --reload
      --reload-dir /app
    healthcheck:
      # Use Python in the image so we don't need curl/wget installed
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:8080/').status==200 else sys.exit(1)\""]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
